# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myqt.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(800, 300)
        Dialog.setMouseTracking(True)
        self.Temperature_Display = QtWidgets.QPushButton(Dialog)
        self.Temperature_Display.setGeometry(QtCore.QRect(0, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.Temperature_Display.setFont(font)
        self.Temperature_Display.setMouseTracking(True)
        self.Temperature_Display.setAutoFillBackground(True)
        self.Temperature_Display.setObjectName("Temperature_Display")
        self.Humidity_Display = QtWidgets.QPushButton(Dialog)
        self.Humidity_Display.setGeometry(QtCore.QRect(0, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.Humidity_Display.setFont(font)
        self.Humidity_Display.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Humidity_Display.setMouseTracking(True)
        self.Humidity_Display.setObjectName("Humidity_Display")
        self.tlabel = QtWidgets.QLabel(Dialog)
        self.tlabel.setGeometry(QtCore.QRect(130, 30, 41, 21))
        self.tlabel.setObjectName("tlabel")
        self.hlabel = QtWidgets.QLabel(Dialog)
        self.hlabel.setGeometry(QtCore.QRect(100, 90, 31, 21))
        self.hlabel.setObjectName("hlabel")
        self.status = QtWidgets.QPushButton(Dialog)
        self.status.setGeometry(QtCore.QRect(0, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setMouseTracking(True)
        self.status.setObjectName("status")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 150, 101, 21))
        self.label.setObjectName("label")
        self.averagetemp = QtWidgets.QPushButton(Dialog)
        self.averagetemp.setGeometry(QtCore.QRect(180, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.averagetemp.setFont(font)
        self.averagetemp.setObjectName("averagetemp")
        self.humavg = QtWidgets.QPushButton(Dialog)
        self.humavg.setGeometry(QtCore.QRect(180, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.humavg.setFont(font)
        self.humavg.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.humavg.setMouseTracking(True)
        self.humavg.setObjectName("humavg")
        self.setalarm = QtWidgets.QPushButton(Dialog)
        self.setalarm.setGeometry(QtCore.QRect(180, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.setalarm.setFont(font)
        self.setalarm.setMouseTracking(True)
        self.setalarm.setObjectName("setalarm")
        self.graphdisplay = QtWidgets.QPushButton(Dialog)
        self.graphdisplay.setGeometry(QtCore.QRect(110, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.graphdisplay.setFont(font)
        self.graphdisplay.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.graphdisplay.setMouseTracking(True)
        self.graphdisplay.setObjectName("graphdisplay")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 160, 67, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 250, 101, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Temperature_Display.setText(_translate("Dialog", "Temperature"))
        self.Humidity_Display.setText(_translate("Dialog", "Humidity "))
        self.tlabel.setText(_translate("Dialog", "temp"))
        self.hlabel.setText(_translate("Dialog", "hum"))
        self.status.setText(_translate("Dialog", "Status"))
        self.label.setText(_translate("Dialog", "conn/disconn"))
        self.averagetemp.setText(_translate("Dialog", "Avg_temp"))
        self.humavg.setText(_translate("Dialog", "Avg_hum"))
        self.setalarm.setText(_translate("Dialog", "Alarm"))
        self.graphdisplay.setText(_translate("Dialog", "Graph"))
        self.label_2.setText(_translate("Dialog", "set alarm"))
        self.label_3.setText(_translate("Dialog", "graph display"))

